# version: "3.8"        --obsolete attribute

services:

  fastapi:
    build:
      dockerfile: fastapi/Dockerfile
    ports:
     - 8080:8080
    networks:
     - deploy_network
    container_name: backend

  streamlit:
    build:
      dockerfile: streamlit/Dockerfile
    depends_on:
     - fastapi
    ports:
     - 8501:8501
    networks:
     - deploy_network
    container_name: frontend

networks:
  deploy_network:
    driver: bridge
      