# version: "3.8"        --obsolete attribute

services:

  backend:
    build:
      context: .
      dockerfile: pima_api/fastapi/Dockerfile
    ports:
     - 8080:80
    networks:
     - deploy_network
    container_name: backend

  frontend:
    build:
      context: .
      dockerfile: pima_api/streamlit/Dockerfile
    depends_on:
     - backend
    ports:
     - 8501:8501
    networks:
     - deploy_network
    container_name: frontend

networks:
  deploy_network:
    driver: bridge
      