name: CML

on: [push]

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/iterative/cml:0-dvc2-base1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: CML Run
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          python pima_api.py

          echo "## CLASSIFICATION REPORT" > report.md
          cat report.json >> report.md
          echo '![](./confusion_matrix.png "Confusion Matrix")' >> report.md

          cml comment create report.md
          
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
