name: CML

on: [push]

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: CHECKOUT
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: iterative/setup-cml@v1
      # - uses: iterative/setup-dvc@v1


      - name: TRAIN
        run: |
          pip install --no-cache-dir -r requirements.txt
          python pima_api.py


      - name: REPORT
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Metrics" > report.md
          cat report.json >> report.md
          echo "## Plots" >> report.md
          echo '![](./confusion_matrix.png "Confusion Matrix")' >> report.md

          cml comment create report.md
          